"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import React from 'react';
import Navbar from '../app/components/Navbar';
import LandingNavbar from "./components/LandingNavbar";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
  title: "DishDash",
  description: "Generated by create next app",
};
*/
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{color:"red"}} className ={inter.className}>
      <LandingNavbar/>

        {children}</body>

    </html>
  );
}
